In [28]:
import numpy as np
L = np.random.random(1000000)
L

array([0.44788084, 0.40879173, 0.43387778, ..., 0.44878077, 0.27204448,
       0.21191663])

In [29]:
%%time
# python自带的聚合函数
sum(L)

CPU times: user 91.1 ms, sys: 548 µs, total: 91.6 ms
Wall time: 91.7 ms


500175.3724208463

In [30]:
%%time
#numpy中的sum
np.sum(L)

CPU times: user 1.08 ms, sys: 142 µs, total: 1.22 ms
Wall time: 687 µs


500175.37242086005

In [32]:
X = np.random.random(10)
X

array([0.299727  , 0.45918442, 0.88443473, 0.45506843, 0.47048329,
       0.93556197, 0.58071138, 0.34720901, 0.54677348, 0.20033433])

In [33]:
np.min(X)

0.200334329534669

In [34]:
np.max(X)

0.9355619715142639

In [35]:
np.sum(X)

5.179488041614025

In [36]:
Y = np.arange(16).reshape(4,-1)
Y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
#列聚合
np.sum(Y,axis=0)

array([24, 28, 32, 36])

In [40]:
#行聚合
np.sum(Y,axis=-1)

array([ 6, 22, 38, 54])

### 其它聚合操作

In [41]:
# 所有元素的乘积，由于第一个元素是0，所以结果为0
np.prod(Y)

0

In [42]:
# 所有元素+1后的乘积
np.prod(Y+1)

20922789888000

In [43]:
# 求平均值
np.mean(Y)

7.5

In [44]:
# 求中位数
np.median(Y)

7.5

In [53]:
#分位点， 代表百分之多少的数据
# 常用用的分位点   0 25 50 75 100
# 通常这五个分位点就能看出数据的分布情况
for percent in(0,25,50,75,100):
    print(np.percentile(Y,q=percent))


0.0
3.75
7.5
11.25
15.0


In [54]:
# 方差
np.var(Y)

21.25

In [55]:
# 标准差
np.std(Y)

4.6097722286464435

In [87]:
# 取标准差为1的正态分布
x = np.random.normal(0,1,size=1000000)
x

array([-0.62843954,  0.14183357, -1.47195499, ...,  0.19327616,
        0.38692664,  0.53198152])

In [57]:
#x的均值 无限接近于0
np.mean(x)

0.00149203292619396

In [58]:
# x在标准差 接近于1
np.std(x)

1.0004229245953757

### 索引

In [59]:
np.min(x)

-4.538811260545467

In [60]:
# 如果想知道上面的最小值是谁？在哪？ 用numpy.argmin(x)来计算
# 运算结果就是最小值的索引
np.argmin(x)

520762

In [61]:
# 查看索引位置的数，就是最小值
x[520762]

-4.538811260545467

In [62]:
np.max(x)

4.750383276311373

In [63]:
np.argmax(x)

16358

In [64]:
x[16358]

4.750383276311373

### 排序和使用索引

In [90]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [91]:
# numpy.random.shuffle(x) 命令对数据进行乱序
np.random.shuffle(x)
x

array([10, 14,  6,  0,  7,  4, 11, 15,  8,  1,  2,  3,  5,  9, 13, 12])

In [68]:
# 使用numpy.sort(x) 对x进行重排序
x = np.sort(x)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [71]:
# 二维矩阵的索引与排序
X = np.random.randint(10,size=(4,4))
X

array([[7, 8, 2, 5],
       [6, 4, 5, 6],
       [7, 1, 9, 9],
       [9, 1, 9, 9]])

In [72]:
# 对二维矩阵进行排序
# 默认是对每行进行排序
np.sort(X)

array([[2, 5, 7, 8],
       [4, 5, 6, 6],
       [1, 7, 9, 9],
       [1, 9, 9, 9]])

In [74]:
# 行排序
np.sort(X,axis=1)

array([[2, 5, 7, 8],
       [4, 5, 6, 6],
       [1, 7, 9, 9],
       [1, 9, 9, 9]])

In [94]:
# 列排序
np.sort(X,axis=0)

array([[6, 1, 2, 5],
       [7, 1, 5, 6],
       [7, 4, 9, 9],
       [9, 8, 9, 9]])

In [95]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [96]:
np.random.shuffle(x)
x

array([ 0, 11, 12,  7,  4,  9,  1, 13, 14, 15,  5,  6,  2, 10,  3,  8])

In [98]:
# 获得排序后的索引
np.argsort(x)

array([ 0,  6, 12, 14,  4, 10, 11,  3, 15,  5, 13,  1,  2,  7,  8,  9])

In [99]:
# 标定点   所选标定点的左侧都比标定点小， 右侧都比标定点大 , 但两侧都是不排序的
np.partition(x,6)

array([ 1,  5,  3,  0,  4,  2,  6,  7,  8, 15, 14, 11,  9, 10, 12, 13])

In [100]:
# 标定点的索引排列
np.argpartition(x,6)

array([ 6, 10, 14,  0,  4, 12, 11,  3, 15,  9,  8,  1,  5, 13,  2,  7])