In [3]:
import numpy

In [2]:
numpy.__version__

'1.14.3'

In [3]:
L = [i for i in range(10)]

In [4]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [17]:
# # List中可以存在不同类型的元素
# 存放不同的类型就意味着效率低下，每次读取或使用都需要类型检查
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [18]:
# python中也有只能存放一种类型的容器， array
# 这种方式降低了python的灵活性，但相对来说也提升了效率
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [21]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

In [23]:
# array还有一个缺点，他只是把存储在其内的数据当作数组或二维数组来看，但是无论是基于数组还是二组二维数组，
# 它没有把这些数据看作是向量或是矩阵，相应的也没为这些数据配备向量相关或矩阵相关的计算，这使得我们在机器
# 学习中使用矩阵也不方便，由此numpy这个模块工具就应运而生
# numpy.array
nparr = numpy.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#操作方式与python的array,list是一样的
nparr[5]

5

In [25]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [26]:
nparr [5] = "machine learning"

ValueError: invalid literal for int() with base 10: 'machine learning'

In [27]:
# 查看numpy.array的数据类型
nparr.dtype

dtype('int64')

In [30]:
# numpy.array有些情况会做自动类型转换
nparr[5] = 5.0
nparr[3] = 3.14
nparr[4] = 4.87
nparr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
nparr2 = numpy.array([1,2,3.0])
nparr2.dtype

dtype('float64')

# 其它创建numpy.array的方法

In [4]:
numpy.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
numpy.zeros(10).dtype

dtype('float64')

In [7]:
numpy.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
numpy.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
numpy.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
numpy.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
numpy.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [17]:
numpy.full(fill_value=555,shape=(3,5))

array([[555, 555, 555, 555, 555],
       [555, 555, 555, 555, 555],
       [555, 555, 555, 555, 555]])

### arange

In [20]:
# 0-20 步长为2的数列
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [22]:
# python是不允许步长值为小数的
[i for i in range(0,2,0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [24]:
# 但是numpy.arange是支持小数的
numpy.arange(0,2,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [25]:
# 如果不填写步长，则默认为1
numpy.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [26]:
# 0-20 之间的等差数列
numpy.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

### random

In [28]:
numpy.random.randint(0,10)

8

In [29]:
# 生成0-10之间的10个数列
numpy.random.randint(0,10,10)

array([1, 8, 7, 0, 2, 5, 9, 6, 9, 6])

In [30]:
# 带上参数名
numpy.random.randint(4,8,size=10)

array([4, 6, 4, 7, 7, 4, 7, 6, 5, 5])

In [31]:
# 调试的时候，需要两次随机数是一样的，这样便与分析结果，这里就会用到随机种子
# 下面这段代码，执行多少次结果的随机数也是相同的（因为计算机在生成随机数时是用随机种子推导出来的）
numpy.random.seed(666)
numpy.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [32]:
numpy.random.seed(666)
numpy.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [33]:
# 生成随机浮点数
numpy.random.random(10)

array([0.28116849, 0.46284169, 0.23340091, 0.76706421, 0.81995656,
       0.39747625, 0.31644109, 0.15551206, 0.73460987, 0.73159555])

In [34]:
numpy.random.random((3,5))

array([[0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197],
       [0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896],
       [0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259]])

In [37]:
# 均值为10， 方差为100的正态分布
numpy.random.normal(10,100)

92.10136919707703

In [38]:
# 均值为0，方差为1的（3，5）的矩阵
numpy.random.normal(0,1,(3,5))

array([[ 0.36712592,  1.65399586,  0.13946473, -1.21715355, -0.99494737],
       [-1.56448586, -1.62879004,  1.23174866, -0.91360034, -0.27084407],
       [ 1.42024914, -0.98226439,  0.80976498,  1.85205227,  1.67819021]])

In [40]:
numpy.random.normal?

In [42]:
help(numpy.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap