# 合并操作

In [1]:
import numpy
x = numpy.array([1,2,3])
y = numpy.array([3,2,1])

In [2]:
x

array([1, 2, 3])

In [3]:
y

array([3, 2, 1])

In [4]:
numpy.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [5]:
z = numpy.array([666,666,666])
z

array([666, 666, 666])

In [6]:
numpy.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [7]:
A = ([[1,2,3],[4,5,6]])
A

[[1, 2, 3], [4, 5, 6]]

In [8]:
# 坚向拼接
numpy.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
# 横向拼接
numpy.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [11]:
# A是 2*3 的一个矩阵，它有两个样本 ； z只是一个一维数组，是包含三个元素的向量，它只有一个样本的
# 如何把z表示的样本融合到A这个矩阵中呢？

numpy.concatenate([A,z])

ValueError: all the input arrays must have same number of dimensions

In [12]:
# 上面的实验证明是不可以的，那么我们需要把z也转换成矩阵，然后再拼接
numpy.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

#### reshape参数说明：
##### 如上面的代码（1，-1）表示： 1表示只有一行，-1表示有多少个元素就插入多少个元素

In [13]:
A2 = numpy.concatenate([A,z.reshape(1,-1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

#### vstack是智能的拼接，比reshape用起来要简单些

##### 一般有vstack就有hstack哟  : )

In [14]:
numpy.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [15]:
B = numpy.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [16]:
numpy.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

# 分隔操作

In [17]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# 把数据切成三断
x1,x2,x3 = numpy.split(x,[3,7])

In [20]:
x1

array([0, 1, 2])

In [21]:
x2

array([3, 4, 5, 6])

In [22]:
x3

array([7, 8, 9])

In [23]:
# 创建一个二维矩阵,并对矩阵进行分隔
A = numpy.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
A1,A2 = numpy.split(A,[2])

In [25]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
A1,A2 = numpy.split(A,(2),axis=1)

In [28]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [29]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [30]:
# 同矩阵合并一样，用axis不够直观，所以矩阵分隔也提供了新的方法 vsplit
upper,lower = numpy.vsplit(A,[2])

In [31]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
# 相应的有vsplit就有hsplit
left , right = numpy.hsplit(A,[2])

In [35]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [36]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [38]:
data = numpy.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
#表示从矩阵右侧的第一行开始分隔
x,y = numpy.hsplit(data,[-1])

In [43]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [44]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])